version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mintdegisn-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mintdegisn
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mintdegisn-network

  backend:
    image: python:3.10-slim
    container_name: mintdegisn-backend
    restart: unless-stopped
    working_dir: /app
    environment:
      MONGO_URL: mongodb://admin:password123@mongodb:27017/mintdegisn?authSource=admin
      DB_NAME: mintdegisn
      JWT_SECRET: mintdegisn-super-secret-jwt-key-2025-docker
      CORS_ORIGINS: http://212.87.221.79:3005,http://localhost:3005
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    networks:
      - mintdegisn-network
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y git gcc && 
        git clone https://github.com/mazisel/mintdesing.git /tmp/repo && 
        cp -r /tmp/repo/backend/* /app/ && 
        pip install --no-cache-dir -r requirements.txt && 
        uvicorn server:app --host 0.0.0.0 --port 8080
      "

  frontend:
    image: node:18-alpine
    container_name: mintdegisn-frontend
    restart: unless-stopped
    working_dir: /app
    environment:
      REACT_APP_BACKEND_URL: http://212.87.221.79:8081
    ports:
      - "3005:3005"
    depends_on:
      - backend
    networks:
      - mintdegisn-network
    command: >
      sh -c "
        apk add --no-cache git && 
        git clone https://github.com/mazisel/mintdesing.git /tmp/repo && 
        cp -r /tmp/repo/frontend/* /app/ && 
        yarn install && 
        yarn build && 
        npx serve -s build -l 3005
      "

volumes:
  mongodb_data:

networks:
  mintdegisn-network:
    driver: bridge
