version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mintdegisn-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mintdegisn
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mintdegisn-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mintdegisn-backend
    restart: unless-stopped
    environment:
      MONGO_URL: mongodb://admin:password123@mongodb:27017/mintdegisn?authSource=admin
      DB_NAME: mintdegisn
      JWT_SECRET: mintdegisn-super-secret-jwt-key-2025-docker
      CORS_ORIGINS: http://localhost:3005,http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - mintdegisn-network
    volumes:
      - ./backend:/app
      - /app/venv

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mintdegisn-frontend
    restart: unless-stopped
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
    ports:
      - "3005:3005"
    depends_on:
      - backend
    networks:
      - mintdegisn-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  mintdegisn-network:
    driver: bridge
